#!/bin/bash

# Super simple IRC bot.

NICK="bitlair"
CHANNEL="#bitlair"
SERVER="irc.smurfnet.ch"
INPORT="31337"

set -eu
set -o pipefail

trap 'kill $(jobs -p)' INT TERM EXIT

loop="/tmp/irc-bot-loop"
mkfifo "$loop"
trap "rm -f $loop" INT TERM EXIT

{
echo "NICK $NICK"
sleep 0.2
echo "USER $NICK +i * :$0"
sleep 6
echo "JOIN $CHANNEL"

# FIXME: Possible race condition between loop and stdin.
tail -f "$loop" &

while true; do
    echo "NOTICE $CHANNEL $(nc -lp "$INPORT" | tr -c -d '[:print:]')"
done
} | \
nc "$SERVER" 6667 | while read message; do
    case "$message" in
        PING*) echo "PONG ${message#PING :}" > "$loop";;
        ERROR*) echo "$message"; exit;;
        *PRIVMSG*) echo "${message}" | sed -nr "s/^:([^!]+).*PRIVMSG[^:]+:(.*)/[$(date '+%R')] <\1> \2/p";;
        *) echo "${message}";;
    esac
done
